config/routes.rb
Rails.application.routes.draw do
  resources :legal_people
  resources :people
  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :athletes
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :person
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  belongs_to :physical_person
end

app/models/class_type.rb
class ClassType < ApplicationRecord
end

app/models/classe.rb
class Classe < ApplicationRecord
  belongs_to :class_type
end

app/models/coach.rb
class Coach < ApplicationRecord
  belongs_to :physical_person
end

app/models/legal_person.rb
class LegalPerson < ApplicationRecord
  belongs_to :person
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :athlete
end

app/models/person.rb
class Person < ApplicationRecord
  has_one :legal_person, dependent: :destroy
  accepts_nested_attributes_for :legal_person
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :coach
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :physical_person
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :physical_person
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/legal_people_controller.rb
class LegalPeopleController < ApplicationController
  before_action :set_legal_person, only: [:show, :edit, :update, :destroy]

  # GET /legal_people
  # GET /legal_people.json
  def index
    @legal_people = LegalPerson.all
  end

  # GET /legal_people/1
  # GET /legal_people/1.json
  def show
  end

  # GET /legal_people/new
  def new
    @legal_person = LegalPerson.new
  end

  # GET /legal_people/1/edit
  def edit
  end

  # POST /legal_people
  # POST /legal_people.json
  def create
    @legal_person = LegalPerson.new(legal_person_params)

    respond_to do |format|
      if @legal_person.save
        format.html { redirect_to @legal_person, notice: 'Legal person was successfully created.' }
        format.json { render :show, status: :created, location: @legal_person }
      else
        format.html { render :new }
        format.json { render json: @legal_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legal_people/1
  # PATCH/PUT /legal_people/1.json
  def update
    respond_to do |format|
      if @legal_person.update(legal_person_params)
        format.html { redirect_to @legal_person, notice: 'Legal person was successfully updated.' }
        format.json { render :show, status: :ok, location: @legal_person }
      else
        format.html { render :edit }
        format.json { render json: @legal_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legal_people/1
  # DELETE /legal_people/1.json
  def destroy
    @legal_person.destroy
    respond_to do |format|
      format.html { redirect_to legal_people_url, notice: 'Legal person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal_person
      @legal_person = LegalPerson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legal_person_params
      params.require(:legal_person).permit(:cnpj, :nomefantasia, :person_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/legal_people_helper.rb
module LegalPeopleHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/legal_people/_form.html.erb
<%= form_for(legal_person) do |f| %>
  <% if legal_person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(legal_person.errors.count, "error") %> prohibited this legal_person from being saved:</h2>

      <ul>
      <% legal_person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cnpj %>
    <%= f.text_field :cnpj %>
  </div>

  <div class="field">
    <%= f.label :nomefantasia %>
    <%= f.text_field :nomefantasia %>
  </div>

  <div class="field">
    <%= f.label :person_id %>
    <%= f.text_field :person_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/legal_people/edit.html.erb
<h1>Editing Legal Person</h1>

<%= render 'form', legal_person: @legal_person %>

<%= link_to 'Show', @legal_person %> |
<%= link_to 'Back', legal_people_path %>

app/views/legal_people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Legal People</h1>

<table>
  <thead>
    <tr>
      <th>Cnpj</th>
      <th>Nomefantasia</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @legal_people.each do |legal_person| %>
      <tr>
        <td><%= legal_person.cnpj %></td>
        <td><%= legal_person.nomefantasia %></td>
        <td><%= legal_person.person.nome %></td>
        <td><%= link_to 'Show', legal_person %></td>
        <td><%= link_to 'Edit', edit_legal_person_path(legal_person) %></td>
        <td><%= link_to 'Destroy', legal_person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Legal Person', new_legal_person_path %>

app/views/legal_people/new.html.erb
<h1>New Legal Person</h1>

<%= render 'form', legal_person: @legal_person %>

<%= link_to 'Back', legal_people_path %>

app/views/legal_people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cnpj:</strong>
  <%= @legal_person.cnpj %>
</p>

<p>
  <strong>Nomefantasia:</strong>
  <%= @legal_person.nomefantasia %>
</p>

<p>
  <strong>Person:</strong>
  <%= @legal_person.person %>
</p>

<%= link_to 'Edit', edit_legal_person_path(@legal_person) %> |
<%= link_to 'Back', legal_people_path %>