config/routes.rb
Rails.application.routes.draw do
  resources :legal_people
  resources :people
  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :athletes
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :person
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  belongs_to :physical_person
end

app/models/class_type.rb
class ClassType < ApplicationRecord
end

app/models/classe.rb
class Classe < ApplicationRecord
  belongs_to :class_type
end

app/models/coach.rb
class Coach < ApplicationRecord
  belongs_to :physical_person
end

app/models/legal_person.rb
class LegalPerson < ApplicationRecord
  belongs_to :person
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :athlete
end

app/models/person.rb
class Person < ApplicationRecord
  has_one :legal_person, dependent: :destroy
  accepts_nested_attributes_for :legal_person
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :coach
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :physical_person
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :physical_person
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/athletes/_form.html.erb
<%= form_for(athlete) do |f| %>
  <% if athlete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(athlete.errors.count, "error") %> prohibited this athlete from being saved:</h2>

      <ul>
      <% athlete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :cpf %>
    <%= f.text_field :cpf %>
  </div>

  <div class="field">
    <%= f.label :sex %>
    <%= f.text_field :sex %>
  </div>

  <div class="field">
    <%= f.label :birth_date %>
    <%= f.date_select :birth_date %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :cell_phone %>
    <%= f.text_field :cell_phone %>
  </div>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :number_street %>
    <%= f.number_field :number_street %>
  </div>

  <div class="field">
    <%= f.label :complement %>
    <%= f.text_field :complement %>
  </div>

  <div class="field">
    <%= f.label :neighborhood %>
    <%= f.text_field :neighborhood %>
  </div>

  <div class="field">
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/athletes/edit.html.erb
<h1>Editing Athlete</h1>

<%= render 'form', athlete: @athlete %>

<%= link_to 'Show', @athlete %> |
<%= link_to 'Back', athletes_path %>

app/views/athletes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Athletes</h1>

<table>
  <thead>
    <tr>
      <th>Cpf</th>
      <th>Sex</th>
      <th>Birth date</th>
      <th>Phone</th>
      <th>Cell phone</th>
      <th>Street</th>
      <th>Number street</th>
      <th>Complement</th>
      <th>Neighborhood</th>
      <th>Cep</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @athletes.each do |athlete| %>
      <tr>
        <td><%= athlete.email %></td>
        <td><%= athlete.login %></td>
        <td><%= athlete.password %></td>
        <td><%= athlete.name %></td>
        <td><%= athlete.cpf %></td>
        <td><%= athlete.sex %></td>
        <td><%= athlete.birth_date %></td>
        <td><%= athlete.phone %></td>
        <td><%= athlete.cell_phone %></td>
        <td><%= athlete.street %></td>
        <td><%= athlete.number_street %></td>
        <td><%= athlete.complement %></td>
        <td><%= athlete.neighborhood %></td>
        <td><%= athlete.cep %></td>
        <td><%= athlete.city %></td>
        <td><%= athlete.state %></td>
        <td><%= link_to 'Show', athlete %></td>
        <td><%= link_to 'Edit', edit_athlete_path(athlete) %></td>
        <td><%= link_to 'Destroy', athlete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New athlete', new_athlete_path %>

app/views/athletes/new.html.erb
<h1>New Athlete</h1>

<%= render 'form', athlete: @athlete %>

<%= link_to 'Back', athletes_path %>

app/views/athletes/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @athlete.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @athlete.cpf %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @athlete.sex %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @athlete.birth_date %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @athlete.phone %>
</p>

<p>
  <strong>Cell phone:</strong>
  <%= @athlete.cell_phone %>
</p>

<p>
  <strong>Street:</strong>
  <%= @athlete.street %>
</p>

<p>
  <strong>Number street:</strong>
  <%= @athlete.number_street %>
</p>

<p>
  <strong>Complement:</strong>
  <%= @athlete.complement %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= @athlete.neighborhood %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @athlete.cep %>
</p>

<p>
  <strong>City:</strong>
  <%= @athlete.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @athlete.state %>
</p>

<%= link_to 'Edit', edit_athlete_path(@athlete) %> |
<%= link_to 'Back', athletes_path %>